### ISSUE TITLE
Ajouter des règles pour Testing-Library

### ISSUE THREAD

**Issue by LucasPerso** [Evaneos/front-config#14]
Histoire d'uniformiser nos tests d'une application à une autre, ça serait pas mal de mettre en place des règles communes. Notamment cet ensemble de règles : https://github.com/testing-library/eslint-plugin-testing-library

Quelques exemples de règles : 
* Usage du `await` avant un `fireEvent`
* Utiliser plutôt `await findBy` que `waitFor + getBy`
* Utiliser plutôt `queryBy` quand on vérifie la disparition d'un noeud DOM

etc.

Qu'en pensez-vous ?

**Comment by fkroockmann** [comment]
Oui ça peut etre cool quelque chose comme ça. Après faut voir comment bien le maintenir, s'assurer qu'il soit lu et compris pour les nouveaux etc..

**Comment by LucasPerso** [comment]
Je pense que ça peut s'accompagner d'une documentation (sur Notion) qui explique les do's and don't des tests RTL à Evaneos
