### ISSUE TITLE
Devrait-on baisser la version des peerDependencies utilisées dans le package ?

### ISSUE THREAD

**Issue by misterbridge** [Evaneos/front-config#4]

**Comment by LucasPerso** [comment]
Pour reprendre ce sujet, je pense que c'est plus simple effectivement d'avoir la majeure de la version utilisée. Ca évite de devoir mettre à jour et les devDeps et les peerDeps.

**Comment by misterbridge** [comment]
Je ne sais pas trop si le bénéfice est intéressant ou non, sachant que si on reste comme aujourd'hui on sera plus enclin à ne pas oublier de mettre à jour les peerdeps.

**Comment by LucasPerso** [comment]
OK, je te propose de ferme l'issue dans cet cas !
